name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Echo raw EC2_HOST (debug)
        run: |
          echo "Raw EC2_HOST (invisible chars shown):"
          echo "${{ secrets.EC2_HOST }}" | cat -A

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -tt ubuntu@54.87.250.8 << 'EOF'
            cd ~/kifaruBackend
            git pull origin main
            npm install
            npm run build
            pm2 restart kifaru || pm2 start dist/main.js --name kifaru
          EOF
